// Typed wrapper around powers.json (456 entries, generated by
// scripts/extract-powers.py -- see PLAN.md §2.3). This is real data, not a
// stub: the dropdown and "#" reroll both read from here from day one.

import raw from './powers.json'
import type { PowerEntry } from '@/types/reference'

export const POWERS: PowerEntry[] = raw as PowerEntry[]

export const POWER_CATEGORIES: string[] = Array.from(new Set(POWERS.map((p) => p.category)))

export function powersByCategory(category: string): PowerEntry[] {
  return POWERS.filter((p) => p.category === category)
}

export function powerByName(name: string): PowerEntry | undefined {
  return POWERS.find((p) => p.name === name)
}

/** '*' (godly) and '**' (cosmic) powers cost extra Power slots -- see powerSlotCost. */
export function powerDisplayName(entry: PowerEntry): string {
  if (entry.tier === 'godly') return `${entry.name} *`
  if (entry.tier === 'cosmic') return `${entry.name} **`
  return entry.name
}

/** How many Power slots a power (by name) consumes: 1 normally, 2 for a
 * '*' (godly) power, 3 for a '**' (cosmic) power. Unknown/blank names cost 1. */
export function powerSlotCost(name: string): number {
  const tier = powerByName(name)?.tier
  if (tier === 'godly') return 2
  if (tier === 'cosmic') return 3
  return 1
}

export interface PowerOptionGroup {
  category: string
  items: { name: string; label: string }[]
}

/** Grouped-by-category options for PrimeVue Select's optionGroup* props. */
export const POWERS_GROUPED: PowerOptionGroup[] = POWER_CATEGORIES.map((category) => ({
  category,
  items: powersByCategory(category).map((p) => ({ name: p.name, label: powerDisplayName(p) })),
}))
