// Typed wrapper around talents.json (211 entries, generated by
// scripts/extract-talents.py -- see PLAN.md §2.4). Real data, not a stub.

import raw from './talents.json'
import type { TalentEntry } from '@/types/reference'

export const TALENTS: TalentEntry[] = raw as TalentEntry[]

export const TALENT_CATEGORIES: string[] = Array.from(new Set(TALENTS.map((t) => t.category)))

export function talentsByCategory(category: string): TalentEntry[] {
  return TALENTS.filter((t) => t.category === category)
}

export function talentByName(name: string): TalentEntry | undefined {
  return TALENTS.find((t) => t.name === name)
}

export interface TalentOptionGroup {
  category: string
  items: { name: string }[]
}

export const TALENTS_GROUPED: TalentOptionGroup[] = TALENT_CATEGORIES.map((category) => ({
  category,
  items: talentsByCategory(category).map((t) => ({ name: t.name })),
}))
